services:
  # ==========================================
  # SERVICE: BACKEND (Spring Boot)
  # (Không cần container Database vì bạn đang dùng SQL Server trên Cloud)
  # ==========================================
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: university-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      # 1. Cấu hình kết nối SQL Server Remote (Gear.host)
      SPRING_DATASOURCE_URL: "jdbc:sqlserver://den1.mssql7.gear.host:1433;databaseName=edudb;encrypt=true;trustServerCertificate=true"
      SPRING_DATASOURCE_USERNAME: "edudb"
      SPRING_DATASOURCE_PASSWORD: "Fy6XV!g5~Isg"

      # 2. Cấu hình gửi Mail (Gmail)
      SPRING_MAIL_HOST: "smtp.gmail.com"
      SPRING_MAIL_PORT: "587"
      SPRING_MAIL_USERNAME: "nguyennam25101999@gmail.com"
      SPRING_MAIL_PASSWORD: "bsqk yevj zxqk zase"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"

      # 3. Cấu hình Hibernate
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"

      # 4. JWT Secret
      APP_JWT_SECRET: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
      APP_JWT_EXPIRATIONMS: "86400000"

      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: INFO
    volumes:
      # Mount thư mục lưu ảnh Avatar ra ngoài máy host để không bị mất ảnh
      - ./uploads:/app/uploads