server:
  port: ${PORT:8080}

spring:
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:nguyennam25101999@gmail.com}
    password: ${MAIL_PASSWORD:bsqk yevj zxqk zase}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  application:
    name: backend

  datasource:
    url: ${DATABASE_URL:jdbc:sqlserver://den1.mssql8.gear.host:1433;databaseName=education11;encrypt=true;trustServerCertificate=true}
    username: ${DATABASE_USERNAME:education11}
    password: ${DATABASE_PASSWORD:Cw86~BTxrx!Y}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
      keepalive-time: 30000
      leak-detection-threshold: 2000

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
    com.edu.university: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

app:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expirationMs: ${JWT_EXPIRATION:86400000}

