spring.application.name=backend

spring.datasource.url=jdbc:sqlserver://den1.mssql7.gear.host:1433;databaseName=edudb;encrypt=true;trustServerCertificate=true
spring.datasource.username=edudb
spring.datasource.password=Fy6XV!g5~Isg

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expirationMs=86400000

spring.jpa.open-in-view=false

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true